# Generated by Django 5.2.4 on 2025-10-21 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyschedule', '0003_availableblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availableblock',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
