# Generated by Django 5.2.4 on 2025-10-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('teaser', models.TextField(help_text='Resumen corto o primeros párrafos')),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, to='content.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='content_sto_is_publ_60347c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(blank=True, to='content.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='content_cha_is_publ_65bdf2_idx')],
            },
        ),
    ]
